### PR TITLE
Init

### PR DESCRIPTION
**Pull request by MadebyAe**
Add stage-0 preset

### CODE REVIEW

**Comment by MadebyAe** [comment]
@mattdesl Hello Matt! — I created this PR that supports babel stage-0 very useful for React new ES6. Cheers!

**Comment by MadebyAe** [comment]
Or maybe use --stage Number ?

**Comment by zeke** [comment]
Hey you might not get a response, as this project is/was an experiment. From the README:

> I will not be actively maintaining this module. See run-js for a more active project in a similar vein.

**Comment by MadebyAe** [comment]
@zeke :(  I love the project name

Thanks!

**Pull request closed without merging**
